Add missing return-type annotation (#119)
Fixes error when compiling with --noImplicitAny flag set:
error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.